spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVICE_NAME:localhost}:${DATABASE_PORT:5432}/${DB_NAME:elmenusdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:secretpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

security:
  jwt:
    issuer: "elmenus-lite"
    token-expiration-seconds: 3600
    public-key: classpath:/keys/public.pem
    private-key: classpath:/keys/private.pem
