package spring.practice.elmenus_lite.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import spring.practice.elmenus_lite.dto.request.MenuCreateRequest;
import spring.practice.elmenus_lite.dto.response.MenuResponse;
import spring.practice.elmenus_lite.model.Menu;

@Mapper(componentModel = "spring")
public interface MenuMapper {
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "restaurant", ignore = true) // Restaurant association set by service
    Menu toMenuEntity(MenuCreateRequest request);


    @Mapping(target = "restaurantId", source = "restaurant.id") // Map nested restaurant ID
    MenuResponse toMenuResponse(Menu menu);
}
